# Generated by Django 4.2.4 on 2023-08-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('descp', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
